### ISSUE TITLE
Transformer implementation end to end training

### ISSUE THREAD

**Issue by Bk073** [aladdinpersson/Machine-Learning-Collection#26]

**Comment by Bk073** [comment]
Can you add the end to end training in the transformer from scratch using pytorch.

**Comment by aladdinpersson** [comment]
There is an example where I have used PyTorchs implementation of transformer for machine translation that you can here [here](https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/Pytorch/more_advanced/seq2seq_transformer/seq2seq_transformer.py). All you would do is import the transformer we implemented from scratch instead of that one and you'd have a full example
